services:
  - type: web
    name: mvp3-attendance
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from app import create_tables; create_tables()" && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
